[theme]
primaryColor = "#176B5B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F7F6"
textColor = "#18312D"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
